# Generated by Django 4.2.1 on 2023-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Realizar pedido'], [1, 'Informar un problema'], [2, 'Felicitaciones']], primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
